### PR TITLE
Upgraded to use newest version of mongo & fixed data volume binds

### PR DESCRIPTION
**Pull request by mut3**
bowline was building and relying on the deprecated `dockerfile/mongodb' 
https://registry.hub.docker.com/u/deprecateddockerfile/mongodb/

mongo has moved to 'library/mongo' and command syntax has changed somewhat
https://registry.hub.docker.com/_/mongo/

I upgraded the build_it and run_it scripts to use the newer and maintained version of mongo. 

Due to an unrelated issue with container permissions I was unable to get the scripts to execute.

On line 30 of `build_it.sh`:
```bash
docker run -d -v $MONGO_DIR:/data/db --name temp_mongo library/mongo
```
(port binding to 27017 is now done automagically by mongo)

This container would exit as soon as it was started, meaning the link on line 36:
```bash 
docker run -it --rm --link temp_mongo:mongo -v $EXAMPLE_DATA:/exampledata/ library/mongo \...
```
would fail, because you cannot link to a dead container.

The `temp_mongo` container was crashing and burning due to an error:
```
chown: cannot read directory `/data/db': Permission denied
```
That chown call comes from line 9 of the `docker_entrypoint.sh` script that is part of the mongo container.
https://github.com/docker-library/mongo/blob/master/3.0/docker-entrypoint.sh

The solution for this error, which would kill any `docker run` command with a `-v` data volume bind to a local directory, is to have the container run in `--privileged` mode, allowing it to access the host file system.
https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration

After adding the `--privileged` flag to lines that had previously error'd out in `build_it.sh` and `run_it.sh` I successfully ran a locally hosted Bowline on my CentOS 7 box with Docker 1.6.0.

### CODE REVIEW

**Comment by dougbtv** [comment]
Awesome work. Looks excellent reviewing on mobile, I'll merge it when I'm back at a legitimate workstation.

Great finds all around, really appreciate it.

**Comment by dougbtv** [comment]
@mut3 -- thanks again! Appreciated it. Realized on your profile, you're also in Burlington, VT. Small world, as I am too. You should come drop by LaboratoryB.org and our spot on pine street at some point, I owe you a beer (or tea, if that's how you roll). Thanks Will.

**Comment by mut3** [comment]
@dougbtv I was planning to sometime soon. I realized that i didnt update the `MONGO_CONNECT_STRING` in `includes/example.config.json` to be `mongo://mongo/bowline` and I just pushed that, you could probably manually do it too.

**Comment by dougbtv** [comment]
Thanks @mut3 -- went ahead and manually corrected it, good eye. It's in master now, too.

**Comment by mut3** [comment]
I noted in https://github.com/dougbtv/bowline/issues/12 issues I believed to be outside the scope of this PR and did not stop the app from running with an attached mongo db

**Pull request merged**
